[tool.poetry]
name = "mypython app"
version = "0.1.0"
description = ""
authors = ["Arnav Patil <arnavpatil455@gmail.com>"]
license = "2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
