[tool.poetry]
name = "mypython app"
version = "3.10"
description = ""
authors = ["Arnav Patil <arnavpatil455@gmail.com>"]
license = "2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"



